services:
  backend:
    build:
      context: ./backend
    container_name: lookbook-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: lookbook-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend